version: 2.0
jobs:
 build:
   docker:
     - image: debian:stretch
   steps:
     - checkout
     - run:
         name: Identify Container
         command: |
           hostname -f
           ip a l
           cat /etc/os-release
     - run:
         name: Show Code
         command: ls -al --color
