version: 2.0
jobs:
  build:
    environment:
      ELASTIC_REPO_KEY: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      ELASTIC_REPO: https://artifacts.elastic.co/packages/6.x/apt
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Install Logstash Repository
          command: |
            apt-get -y -qq update
            apt-get -y install apt-transport-https curl gnupg
            curl "$ELASTIC_REPO_KEY" | apt-key add -
            echo "deb $ELASTIC_REPO stable main" | tee -a /etc/apt/sources.list.d/elastic.list
            apt-get -y -qq update
      - run:
          name: Install Java Runtime
          # Elastic Co's Logstash packages do not include run-time deps,
          # so you have to install the JRE manually.  When trying to
          # roll this into one run of apt-get, the logstash pkg install
          # scripts failed, so we split it out here.
          command: |
            apt-get -y install default-jre
            java -version
      - run:
          name: Install Logstash
          command: apt-get -y install logstash=1:6.4.0-1
      - run:
          name: Install Testing Tools
          command: apt-get -y install iproute2 tcpreplay jq
     # - checkout
     # - run:
     #     name: Identify Container
     #     command: |
     #       hostname -f
     #       ip a l
     #       cat /etc/os-release
     # - run:
     #     name: Show Code
     #     command: ls -al --color
