version: 2.0
jobs:
  build:
    environment:
      LOGSTASH_CT: 307937454286.dkr.ecr.us-east-1.amazonaws.com/empatico/logstash
      PROD_LOGSTASH_ADDR: 172.31.15.184
    machine: true
    steps:
      - checkout

      - run:
          name: Retrieve And Launch Logstash Test Container
          command: |
            mkdir artifacts

            $(aws ecr get-login --no-include-email --region us-east-1)

            docker run -d --name=logstash \
            -v $(pwd)/conf:/etc/logstash/conf.d \
            -v $(pwd)/artifacts:/artifacts \
            $LOGSTASH_CT
            
      - run:
          name: Extract Container Addresses
          command: |
            IP_ADDR=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' logstash)
            MAC_ADDR=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.MacAddress}}{{end}}' logstash)
            echo IP_ADDR=$IP_ADDR | tee -a $BASH_ENV
            echo MAC_ADDR=$MAC_ADDR | tee -a $BASH_ENV
            
      - run:
          name: Install Testing Tools
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y install tcpdump tcpreplay realpath
            gem install --no-rdoc --no-ri rspec json_spec
            
      - run:
          name: Rewrite Test Capture For Target Logstash Container
          command: |
            tcprewrite --fixcsum \
            --dstipmap=${PROD_LOGSTASH_ADDR}/32:$IP_ADDR/32 \
            --enet-dmac=$MAC_ADDR \
            -i spec/fixtures/core_gelf_20181025/orig.pcap \
            -o test.pcap
            sudo tcpdump -c 3 -enr test.pcap | grep -P "$MAC_ADDR.+?$IP_ADDR"
            
      - run:
          name: Replay Capture Against Logstash Container
          command: |
            ./bin/wait-for-it.sh --host=$IP_ADDR --port=5514 --timeout=300
            sudo tcpreplay -i docker0 --pps 100 test.pcap

      - run: 
          name: Stop Logstash And Save Daemon Logs
          command: |
            docker stop logstash
            docker logs logstash > artifacts/logstash_daemon.log
          
      - run:
          name: Run Tests
          command: |
            # Logstash outputs a series of JSON objects but Rspec's
            # validator wants a single JSON document
            perl -i -0pe 's! \}\s*\n\s*\{ ! },\n{ !xsg' artifacts/test_output.json
            rspec
          
      - store_artifacts:
          path: artifacts
          destination: logstash
