version: 2.0
jobs:
  build:
    environment:
      ELASTIC_REPO_KEY: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      ELASTIC_REPO: https://artifacts.elastic.co/packages/6.x/apt
      PRIMARY_NET_IFACE: eth0
      PROD_LOGSTASH_ADDR: 172.31.15.184
    # docker:
    #   - image: debian:stretch
    machine: true
    steps:
      - checkout
      - run:
          name: Extract Container Addresses
          command: |
            IP_ADDR=$( ip a l dev $PRIMARY_NET_IFACE | perl -ne 'm!inet\s+((?:\d+\.){3}\d+)! && print "$1"')
            MAC_ADDR=$(ip a l dev $PRIMARY_NET_IFACE | perl -ne 'm!link/ether\s+((?:[a-f\d]{2}:){5}[a-f\d]{2})!i && print "$1"')
            echo IP_ADDR=$IP_ADDR | tee -a $BASH_ENV
            echo MAC_ADDR=$MAC_ADDR | tee -a $BASH_ENV
      - run:
          name: Install Logstash Repository
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y install apt-transport-https curl gnupg
            curl "$ELASTIC_REPO_KEY" | sudo apt-key add -
            echo "deb $ELASTIC_REPO stable main" | sudo tee -a /etc/apt/sources.list.d/elastic.list
            sudo apt-get -y -qq update
      - run:
          name: Install Java Runtime
          # Elastic Co's Logstash packages do not include run-time deps,
          # so you have to install the JRE manually.  When trying to
          # roll this into one run of apt-get, the logstash pkg install
          # scripts failed, so we split it out here.
          command: |
            sudo apt-get -y install default-jre
            java -version
      - run:
          name: Install Logstash
          command: sudo apt-get -y install logstash=1:6.4.0-1
      - run:
          name: Install Testing Tools
          command: sudo apt-get -y install iproute2 tcpdump tcpreplay jq
      - run:
          name: Rewrite Test Capture For This Container
          command: |
            tcprewrite --fixcsum -i test/caps/latest.pcap -o test.pcap --dstipmap=${PROD_LOGSTASH_ADDR}/32:$IP_ADDR/32 --enet-dmac=$MAC_ADDR
            sudo tcpdump -c 10 -enr test.pcap | grep -P "$MAC_ADDR.+?$IP_ADDR"
      - run:
          name: Replay Capture And Process With Logstash
          command: |
            sudo cp logstash.conf.test /etc/logstash/conf.d/logstash.conf
            /usr/share/logstash/bin/logstash --path.settings=/etc/logstash > logstash.log 2>&1 &
            sudo tcpreplay -i $PRIMARY_NET_IFACE --pps 100 test.pcap
      - store_artifacts:
          path ./logstash.log
      - store_artifacts:
          path ./logstash.out.json
